name: asgard_core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_staggered_grid_view: ^0.6.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  gap: ^2.0.0
  sliver_tools: ^0.2.5
  flutter_svg: ^1.0.3
  tap_builder: ^0.3.4

dev_dependencies:
  test_utils:
    path: ../test_utils 
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
  fonts:
    - family: asgard_icons
      fonts:
        - asset: packages/asgard_core/fonts/asgard_icons.ttf
    - family: Poppins
      fonts:
        - asset: packages/asgard_core/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: packages/asgard_core/fonts/Poppins-Bold.ttf
          weight: 700
